# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - bioc-release
  - bioc-devel
cache: packages
apt-packages:
  - infernal
  - r-cran-xml
bioc_packages:
  - BiocCheck
  - ShortRead
bioc_check: true
after_success:
  - Rscript -e 'covr::codecov()'
